name: Digest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0/30 * * * *'

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./digester -s ${{ secrets.digester_server }} -c ${{ secrets.digester_callback }}
